# Existence

The theorem which will ultimately be established in section 4 relies
upon a fundamental theorem in number theory – in fact **the**
fundamental theorem. The Fundamental Theorem of Arithmetic states that
every positive integer, except 1, can be expressed uniquely as a product
of primes.

Proof of this theorem can be found in [11, section 2.10].

The proof which established the existence of Room squares will rely upon
various other theorems which collectively establish the existence of all
Room squares with prime side, except 3 and 5. Then multiplication
theorems will be developed to establish the existence of composite Room
squares (those whose side is the product of two or more primes). Clearly
if the prime Room squares can be proven to exist, and hence composite
Room squares, the fundamental theorem will allow us to state that all
Room squares exist with odd positive integer side. Apart from a few
exceptional cases, this is basically what we wil be able to do.

Starters, Adders and Cyclic Room Squares
----------------------------------------

```{r, echo = FALSE, results='asis'}
t <- data.frame(
  "0" = c("∞0", "45", "31", "  ", "62", "  ", "  "),
  "1" = c("  ", "∞1", "56", "42", "  ", "03", "  "),
  "2" = c("  ", "  ", "∞2", "60", "53", "  ", "14"),
  "3" = c("25", "  ", "  ", "∞3", "01", "64", "  "),
  "4" = c("  ", "36", "  ", "  ", "∞4", "12", "05"),
  "5" = c("16", "  ", "40", "  ", "  ", "∞5", "23"),
  "6" = c("34", "20", "  ", "51", "  ", "  ", "∞6")
)

colnames(t) <- 0:6
rownames(t) <- 0:6
pander::pandoc.table(t)
```

**Figure 16 Cyclic Room square**

The Room square in Figure 16 has a special property. The pairs in any
element of the array are obtained by simply adding 1 (mod 7) to the pair
in the element immediately above and to the left; along with the
condition that $$\infty+1 = \infty$$ This special property means that
the entire square can be determined by the pairs in the first row, with
successive rows being developed in a cyclical manner according the
simple addition rule. We call squares like the one in Figure 16 *cyclic*
Room squares.\
\
Also notice that $\{\infty,i\}$ occurs in position $(i,i)$. A square
with this property is said to be *standardised*. It is important to
realise that any Room square can be standardised. As mentioned
previously neither interchanging the rows or columns nor permuting the
symbol-set on which the Room square is based has any effect of the
\`\`Room"-ness of that square.\
\
The significance of cyclic Room squares is that the problem of
constructing a Room square is (potentially) reduced to that of finding
an appropriate first row. These rows cannot be chosen arbitrarily, both
the pairs used and the positions in which they appear need to satisfy
certain criteria, but when they do exist a corresponding Room square
always exists. So proving the existence of this subclass of Room squares
is a matter only of proving the existence of these special first rows.

### Finding a starter

Suppose we wish to construct another Room square of the same size as
Figure 16 based on the same symbols. This new square will also be
standardized so we need only determine the three pairs that accompany
$\{0,\infty\}$ in the first row (the starter), and the positions they
occupy.\
\
The set we will use to build our starter will be {1,2,...,6}.\
\
Each member of this set must occur exactly once in the pairs of the
starter – in order to satisfy the row condition for a Room square.
Because of the cyclical construction the condition is automatically true
for successive rows if true for the first.\
\
Consider the existence in Figure 16 of an arbitrary pair $\{a,b\}$. We
know one of the following must be true.\
\
Either:
$$\{2+i,5+i\}=\{a,b\} \hspace{0.5cm} \mathrm{or} \hspace{0.5cm} \{1+i,6+i\}=\{a,b\} \hspace{0.5cm} 
\mathrm{or} \hspace{0.5cm} \{3+i,4+i\}=\{a,b\} \hspace{0.5cm} \mathrm{for} \hspace{0.1cm} i=0,1,2,...,6$$
Say $a-b=1$. Then $\{2+i,5+i\}=\{a,b\}$ could never be true because
$(2+i)-(5+i)=-3($mod $ 7)=4$ and $(5+i)-(2+i)=3$. Similarly, the
differences in $\{1,6\}$ are $\pm5$ so $\{a,b\}$ couldn’t be generated
from $\{1,6\}$.\
\
However, $(4+i)-(3+i)=1$ so $\{a,b\}$ will inevitably be generated by
$\{3,4\}$ for some value of $i=0,1,...,6$.\
e.g. $\{2,3\}=\{3+6,4+6\}$\
\
Because $a$ and $b$ separately take on all values from
$\{0,1,2,...,6\}$, their differences will similarly take on all these
values (except 0 because there are no pairs of the form $\{a,a\}$) and
so an essential property for the starter must be that the six
differences generated by its three pairs contain all of
$\{1,2,...,6\}$.\
\
When a starter satisfies this property, and the condition that the pairs
contain in their union all of $\{1,2,...,6\}$, it is clear that it will
inevitably generate the correct pairs which populate a 7x7 Room square.
There are three pairs in the starter, each generates seven unique pairs
under cyclical construction, which along with the seven pairs generated
by $\{0,\infty\}$ counts for all the 28 unordered pairs from
$\{\infty,0,1,...,6\}$.\
A starter for larger Room squares of course has to obey the same
criterion. We include a general definition based on [8]:\
(1,0)<span>450</span>\
*Definition:* If $G$ is an additive Abelian group of order $g$, then a
*starter* in $G$ is a set of unordered pairs:
$$S=\{\{s_i,t_i\}:1 \leq i \leq (g-1)/2\}$$ which satisfies these
properties:

1.  $\{s_i:1 \leq i \leq (g-1)/2\} \cup \{t_i : 1 \leq i \leq (g-1)/2\} = G \backslash \{0\}$

2.  $\{\pm (s_i - t_i ) : 1 \leq i \leq (g-1)/2 \} = G \backslash \{0\}$

(1,0)<span>450</span>\
\
Whenever we have any $t$ sets $D_1,...,D_t$ each of size $k$ in which
each non-zero member of an additive abelian group can be represented as
a difference between members of the $D_i \lambda$ times, we say those
sets form a ***difference system***.\
Much use will be made of difference systems throughout this work.\
Notice that the definition of a starter presumes standardization, and
therefore that $\{\infty,i\}$ is in position $(i,i)$.\
The following pairs form a starter in $G=\{0,1,2,...,6\}$ (an additive
abelian group with order $g=7$.)
$$\{1,3\} \hspace{1cm} \{2,6\} \hspace{1cm} \{4,5\}$$ Property 1 is
satisfied because
$\{1,3\} \cup \{2,6\} \cup \{4,5\} = G \backslash \{0\}$\
Property 2 is also satisfied because
$$\{1-3=5,3-1=2,2-6=3,6-2=4,4-5=6,5-4=1\}=\{1,2,3,4,5,6\}=G\backslash \{0\}$$
Hence

   $\infty 0$   13   26   45
  ------------ ---- ---- ----
   $\infty 1$   24   30   56
   $\infty 2$   35   41   60
   $\infty 3$   46   52   01
   $\infty 4$   50   63   12
   $\infty 5$   61   04   23
   $\infty 6$   02   15   34

**Table 1**

are all the unordered pairs from $\{\infty,0,1,...6\}$ sorted into seven
rows that contain each of $\{\infty,0,1,...,6\}$ exactly once. ALl that
remains is to determine the columns.

### Finding an adder

In constructing the starter we made use of the fact that each row has to
contain each symbol exactly once and all unordered pairs from the symbol
set have to occur exactly once in the whole array. The remaining
condition – namely, that each symbol must occur once in each column – is
now employed to finish the construction.\
\
Again, because of the cyclical nature of Room squares generated from
starters we can be sure that if one column contains each member of the
symbol set, all columns will.\
\
Also, because we have decided to construct a standardized Room Square we
know that column $i$ contains $\{\infty,i\}$. So the final column
(column 6) contains $\{\infty,6\}$, and depending on where we place the
starter pairs it will also include:
$$\{1,3\}+x \hspace{1cm} \{2,6\}+y \hspace{1cm} \{4,5\}+z$$ For some
distinct values of $x,y$ and $z$ (only one pair allowed per box).\
Considering that the new pairs to form column 6 must contain in their
union each of $\{0,1,2,...,5\}$ we build the following table.

   $x$   $13+x$   $y$   $26+y$   $z$   $45+z$
  ----- -------- ----- -------- ----- --------
   $0$     13      0      26      0      45
   $1$     24      1      30      1      56
   $2$     35      2      41      2      60
   $3$     46      3      52      3      01
   $4$     50      4      63      4      12
   $5$     61      5      04      5      23

**Table 2**

Our task is simply to determine three unique values for $x,y$ and $z$
such that $13+x,26+y$ and $45+z$ contain in their union each of
$\{0,1,2,...,5\}$. These values will then determine the positions to
place 13, 26 and 45 in row 1.\
\
Choosing 4 from the first column corresponds to having 50 appear in the
final column of the Room Square and forces the selection of $y=2$ from
the next column of the table, (41 being the only pair not containing any
of the already used 5,6 or 0). 23 is the only possible choice from the
final column, accompanied by a value of $z=5$. These three numbers are
known as an *adder* corresponding to the starter 13,26,45. This is not
necessarily the only adder.\
\
If 50 is to be generated in the final column of the Room square by the
pair 13 in the first row, then 13 must go in column $7-4=3$. Similarly
26 has to be put in column $7-2=5$ and 45 in $7-5=2$.\
We can now construct our cyclic room square.

   $\infty 0$       45           13           -            26           -            -       
  ------------ ------------ ------------ ------------ ------------ ------------ ------------ --
       -        $\infty 1$       56           24           -            30           -       
       -            -        $\infty 2$       60           35           -            41      
       52           -            -        $\infty 3$       01           46           -       
       -            63           -            -        $\infty 4$       12           50      
       61           -            04           -            -        $\infty 5$       23      
       34           02           -            15           -            -        $\infty 6$  

**Figure 17**

In general, we define an adder by considering the elements which must
accompany $\{\infty,0\}$ in column 0. Therefore an adder is defined in
the following way:\
(1,0)<span>450</span>\
An *adder* for a starter $S=\{\{s_i,t_i\}: 1 \leq i \leq (g-1)/2 \}$ is
a set of $(g-1)/2$ distinct non-zero elements $a_1,a_2,...,a_{(g-1)/2}$
of $G$ such that:
$s_1 + a_1,t_1 + a_1,s_2 + a_2,...,s_{(g-1)/2} + a_{(g-1)/2}, t_{(g-1)/2}+a_{(g-1)/2}$
are precisely all the non-zero elements of $G$.\
(1,0)<span>450</span>\
The *starter-adder* method employed in the above example was introduced
in 1968[^4] by Stanton and Mullin [23], who used it to construct Room
squares of side 11. They also went on to apply the method to larger
squares and gave the first real suggestions that the number of Room
squares is infinite.\
\
Two simple Lemmas given by Stanton and Mullin demonstrated that the
problem of finding starters for larger Room squares was straightforward.
In fact they can be guaranteed always to exist, and the only difficulty
comes from finding a corresponding adder, which is not guaranteed to
exist.

#### Lemma 3.2.1

\
In an additive abelian group $G$ of order $g=2n-1$, then pairs
$$\{n-1,n\},\{n-2,n+1\},\{n-3,n+2\},\{n-4,n+3\},...\{1,2n-2\}$$ are a
starter for a Room square of side $2n-1$.\
\
*Example 3.2*\
A Room square of side $2n-1=19$.\
$n=10, G=Z_{19}$\
\
The set of pairs\
$S_{19} = \{\{9,10\},\{8,11\}, \{7,12\}, \{6,13\}, \{5,14\}, \{4,15\}, \{3,16\}, \{2,17\}, \{1,18\}\}$\
is a starter.\
\
Indeed, the differences are\
$\{\pm(10-9),\pm(11-8),\pm(12-7),\pm(13-6),\pm(14-5),\pm(3-16),\pm(2-17),\pm(18-1)\}$\
$=\{1,18,3,16,5,14,7,12,9,10,8,11,6,13,4,15,2,17\}=G \backslash \{0\}$

#### Lemma 3.2.2

\
In the Galois field of order $k-1$, with primitive root $a$ the
following pairs form a starter for a Room square of side $k$.
$$\{a,a^n\},\{a^2,a^{n+1}\},\{a^3,a^{n+2}\},...,\{a^{n-1},a^{2n-2}\}$$
*Example 3.3*\
A Room square of side $2n-1=23$. $n=12$. $a=5$.\
The set of pairs
$$S_{23}=\{\{5,5^{12}\},\{5^2,5^{13}\},\{5^3,5^{14}\},...,\{5^{11},5^{22}\}\}$$
$$=\{\{5,18\},\{2,21\},\{10,13\},\{4,19\},\{20,3\},\{8,15\},\{17,6\},\{16,7\},\{11,12\},\{9,14\},\{22,1\}\}$$
is a starter.\
\
On closer inspection the two types of starters are identical[^5] , with
a general element being of the form $$\{j,-j\}$$ Starters of this form
are called *patterned* starters.\
\
Stanton and Mullin went on to show that using the method outlined in
Example 2.1 they could find adders corresponding to the patterned
starters for $k=7,11,13,15,17$. They had problems with 9 (but were able
to construct one using a different method) and finding it too laborious
for $k>19$ they developed an algorithm which, when implemented in
Fortran, was able to find patterned starters with adders for all odd $k$
up to 49, with no further gaps. Suggesting the possibility (which they
conjectured) that there are Room squares for all odd side greater than
5.\
\
They also found an interesting result regarding the number of Room
Squares which could be obtained from patterned starters, summarised in
Table 3.

   Value of $k$                          Number of PRS
  -------------- --------------------------------------------------------------
        7                                      2
        9                                      0
        11                                     4
        13                                     8
        15                                     44
        17                                    416
        19        The programme was turned off after the production of 967 PRS

**Table 3**

Stanton & Mullin’s results suggest that the number of PRS (patterned
Room squares) increases very rapidly. Which, bearing in mind that the
PRS are a sub-class of CRS (cyclic Room squares), which are in turn a
sub-class of Room squares, implies that there are vast numbers of Room
squares of large order.\
\
Before introducing a class of starters for which the existence of a
corresponding adder is guaranteed we quickly confirm that when a starter
and adder exist then a Room square will always result. This seems
obvious from the method outlined in the previous section, but now we
prove it explicitly.

#### Theorem 3.2.1

[17]\
If an Abelian group $G$ of odd order $2n-1$ admits a starter and an
adder, then there exists a Room square of order $2n$.\
\
*Proof*\
A square is constructed on the set $G \cup \{\infty\}$, where $G$ is an
additive Abelian group of order $2n-1$.
$$G=\{g_0=0,g_1,g_2,...,g_{2n-2}\}$$ The columns and rows of the square
are labelled as follows

           $g_0$   $g_1$   $g_2$   ...   $g_{2n-1}$
  ------- ------- ------- ------- ----- ------------
   $g_0$
   $g_1$
   $g_2$

   $g_0$

**Figure 18**

If a starter $\{\{s_1,t_1\},\{s_2,t_2\}...\{s_{n-1},t_{n-1}\}\}$ and an
adder $\{a_1,a_2,...,a_{n-1}\}$ can be ontained from $G$ and if the
square is populated by pairs of elements from $G$ according to the
following rules:

1.  $\{\infty,g_i\}$ goes in $(g_i,g_i)$

2.  While $\{s_i+g_i,t_i+g_i\}$ goes in $(g_i,g_i-a_i)$

for all $g_i \in G$. The remaining square will be a Room square on
$G \cup \{\infty\}$.\
*Proof*

1.  Row $g_0=0$, contains the pairs $\{s_i,t_i\}:1 \leq i \leq n-1$,
    which are the elements of the starter, hence all of
    $G \backslash \{0\}$. These pairs are accompanied by $\{\infty,0\}$,
    so row 0 contains all of $G \cup \{\infty\}$. Subsequent rows simple
    contain a permutation of the same elements, hence the *row property*
    of Room squares is satisfied for all rows.

2.  As mentioned before, the starter forms a difference system in
    $G \backslash \{0\}$, so all unordered pairs of this set occur along
    with all unordered pairs of the form
    $\{\infty,g_i\}: 1 \leq i \leq n-1$, hence *all unordered pairs
    from* $G \cup \{\infty\}$ *occur* in the square exactly once.

3.  All pairs of the form $\{s_i+a_i,t_i+a_i\}$ go in $(a_i,0)$, i.e.
    column 0. According to the definition of a starter these pairs are
    all of $G \backslash \{0\}$, and we know that $\{\infty,0\}$ is also
    in column 0. So the first column, and hence all others, contains all
    of $G \cup \{\infty\}$, thus satisfying the *column property* of
    Room squares.

Strong Starters
---------------

The next state in proving the existence of Room squares came about, not
by continuing to try to find adders for starters that were already known
(the patterned starters, for example), but when Mullin & Nemeth in [17],
discovered a class of starters that generated their own adders.

#### Theorem 3.3.1

[17]\
*Suppose a starter*
$\{\{s_1,t_1\},\{s_2,t_2\},...,\{s_{(g-1)/2},t_{(g-1)/2}\}\}$ *exists,
such that the sums of each pair*\
$(s_1+t_1,s_2+t_2, etc...)$ *are all distinct and non-zero, then that
starter is said to be strong, and*
$$A(S)=\{a_i = -(s_i+t_i):1 \leq i \leq (g-1)/2\}$$ *is an adder for a
starter.\
\
Proof*

(i) *The $a_i$ are all distinct and non-zero*\
    All the $(s_i+t_i)$ are, by definition, distinct and non-zero.
    Therefore all the $a_i=-(s_i+t_i)$ are distinct and non-zero.

(ii) $s_1 + a_1, t_1 + a_1, s_2 + a_2,..., s_{(g-1)/2}, t_{(g-1)/2}+a_{(g-1)/2}$
    *are precisely all the non-zero elements of* $G$.

    <span>l</span> $s_1+a_1=s_1-(s_1+t_1)=-t_1=t_{(g-1)/2}$\
    $t_1+a_1=t_1-(s_1+t_1)=-s_1=s_{(g-1)/2}$\
    \
    $s_{(g-1)/2} + a_{(g-1)/2} = -t_{(g-1)/2} = t_1$\
    $t_{(g-1)/2} + a_{(g-1)/2} = -s_{(g-1)/2} = s_1$\

    Are all the non-zero elements of $G$ in reverse order.

(Notice that the patterned starter is not strong, on the contrary, the
sums of its pairs are all identical.)\
\
*Example 3.3.1*\
The pairs $(5,7)(11,6)(2,8)(9,12)(10,1)(3,4)$, constitute a strong
starter for a Room square of side 13, based on $G=Z_{13}$\
\
*Proof*\
Firstly, the pairs satisfy the conditions for being a starter, as the
union of all pairs is equal to $G \backslash \{0\}$, and similarly the
differences are all of $G\backslash \{0\}$.\
Secondly the sums of the pairs, respectively 12,4,10,8,11,7, are all
distinct and non-zero.\
Therefore an adder is $\{-12,-4,-10,-8,-11,-7\}=\{1,9,3,5,2,6\}$\
So the following is a legitimate first row for a cyclic Room square of
order 14.

   $\infty,0$   –   –   –   11,6   –   –   3,4   9,12   –   2,8   1,10   5,7
  ------------ --- --- --- ------ --- --- ----- ------ --- ----- ------ -----

Mullin and Nemeth originally discovered strong starters for Room squares
embedded within another type of combinatorial design, known as a Steiner
triple system. With these they were able to prove that Room squares
exist for all sides $v=1$ mod 6. Rather than examine this approach we
move on to a type of starter which provides its own adder.

The Mullin-Nemeth Starters
--------------------------

If $x$ is a primitive element in $G=GF(p^n)$, then the elements
$x^1,x^2,...,x^{p^n-1}=1$ are, by definition, all of
$G \backslash \{0\}$. Alternatively, we can write $G \backslash
\{0\}=\{x^0=1,x^1,..., x^{p^n-2}\}$.\
\
*Example 3.4.1*\
The field $GF(23)$ has a primitive root $x=5$, because\
$5^0=1,$ $5^1=5,$ $5^2=2,$ $5^3=10,$ $5^4=4,$ $5^5=20,$ $5^6=8,$
$5^7=17,$ $5^8=16,$ $5^9=11,$ $5^{10}=9,$ $5^{11}=22,$ $5^{12}=18,$
$5^{13}=21,$ $5^{14}=13,$ $5^{15}=19,$ $5^{16}=3,$ $5^{17}=15,$
$5^{18}=6,$ $5^{19}=7,$ $5^{20}=12,$ $5^{21}=14$ are all the non-zero
elements of $GF(23)$.\
\
Mullin & Nemeth in [17] used the theory of primitive elements to create
strong starters in the additive group of (nearly) any Galois Field of
prime power order. Which, because Theorems 3.2.1 and 3.3.1 were already
known, was equivalent to proving the existence of Room squares for
(nearly) all orders $p^n+1$. Before introducing the general construction
for these starters, we illustrate the basic method with a couple of
examples of particular cases.\
\
*Example 3.4.2*\
We can create a strong starter from Example 2.5 simply by pairing the
elements in the order in which they were generated.\
i.e.
$S=\{\{1,5\},\{2,10\},\{4,20\},\{8,17\},\{16,11\},\{9,22\},\{18,21\},\{13,19\},\{3,15\},\{6,7\},\{12,14\}\}$\
is a strong starter.\
*Proof*\
Obviously each member of $GF(23)$ occurs once, because of the definition
of a primitive root.\
The differences
$$\{\pm 4, \pm 8, \pm 7, \pm 9, \pm 10, \pm 5, \pm 3, \pm 6, \pm 11, \pm 1, \pm 2\}$$
are similarly all of $GF(23)$, so $S$ is a starter. The sums
$$\{6,12,1,2,4,8,16,9,18,13,3\}$$ are all unique, and therefore $S$ is
strong and $$A=\{17,11,22,21,19,15,7,14,5,10,20\}$$ is an adder for
$S$.\
So, the following row will generate a Room square of order 24 under
cyclic construction.

<span>-1.66cm</span>

   $\infty,0$   4,20   8,17   12,14   16,11   -   1,5   -   9,22   13,19   -   -   2,10   6,7   -   -   18,21   -   3,15   -   -   -   -
  ------------ ------ ------ ------- ------- --- ----- --- ------ ------- --- --- ------ ----- --- --- ------- --- ------ --- --- --- ---

\
This is an example of the simplest case of the general theorem of
Mullith & Nemeth, where the Galois field is $Z_p$ (the integers mod
$p$), with $p=23=3($ mod $4)$ a prime.\

#### Theorem 3.4.1 [1]

\
*If $p=4m+3$ is prime, $m \geq 1$, then*
$$S=\{\{x^0,x^1\},\{x^2,x^3\},...,\{x^{4m},x^{4m+1}\}\}$$ *is a strong
starter in $Z_p$, and hence a Room square of order $p+1$ exists.*\
\
Example 3.4.2 took $m=5$ and $x=5$.\
\
A slightly more general version of Theorem 3.4.1, which we prove
instead, involves any field of prime power order where $p^n=2t+1$, with
$t>1$ and odd. Of course, when $p^n$ is not prime, the field will no
longer be the integers mod $p$, instead the primitive element will be an
irreducible polynomial whose coefficients belong to $Z_p$.

#### Theorem 3.4.2 [16]

\
If $p^n=2t+1=3($mod $4)$ then
$$S=\{\{x^0,x^1\},\{x^2,x^3\},...,\{x^{2t-2},x^{2t-1}\}\}$$ is a strong
starter in $GF(p^n),(p^n \neq 3)$\
\
*Proof*\
$x$ is a primitive element, so the elements in the starter are all the
non-zero members of $GF(P^n)$.\
The differences are, respectively
$$\pm x^0(1-x), \pm x^2 (1-x), ... , \pm x^{2t-2}(1-x)$$ $(1-x)$ is a
non-zero ($x=1$ is not primitive) member of $GF(p^n)$. So in order to
show that these differences are all the $2t$ non-zero members of
$GF(p^n)$ we merely need to prove that the $2t$ differences are all
distinct and non-zero.\
All the differences can be written $\pm x^{2i}(1-x), 0 \leq i \leq t-1$\
$(1-x) \neq 0$\
$x^{2i}(1-x)=x^{2j}(1-x)$\
$\Rightarrow x^{2i}=x^{2j} \Rightarrow i=j$,\
because $0 \leq 2i,2j \leq 2t-2 < p^{n-1}$, and the primitive element,
by definition, produces each element of $GF(p^n)$ exactly once as the
indices range from 0 to $p^{n-1}$.\
Similarly $-x^{2i}(1-x)=-x^{2j}(1-x)$ only when $i=j$.\
So all the positive differences are unique, similarly the negative.\
However, there remains a possibility for repetition when the signs are
opposite: $$x^{2i}(1-x)=-x^{2j}(1-x) \hspace{1cm}...(1)$$ Either $i=j$
or $i \neq j$\
Let $i=j,$ $(1)$ becomes $x^{2i}+x^{2i}=0, \Rightarrow 2x^{2i}=0$, bit
$i$ takes values $0...t-1$, so $x^2=0$ when $i=1$, contradicting the
order of the primitive element.\
In the $i \neq j$ case, we assume (without loss of generality) that
$i<j$ and write

$x^{2i} = -x^{2j}$\
as $x^{2i}(1+x^{2j-2i})=0$\
$\Rightarrow x^{2j-2i}=-1$

but in $GF(2t+1)$, $x^{\frac{1}{2}(q-1)}=x^t=-1$ $$2j-2i=t$$ but this is
a contradiction as we insisted that $t$ be odd. So $S$ is a starter.\
\
To prove that $S$ is strong we simply note that the sums can be written:

$x^0(1+x)$, $x^2(1+x)$, ..., $x^{2t-2}(1+x)$

$1+x=0 \Rightarrow x = -1$ is only true when $p^n=3$. So
$(1+x) \neq 0$.\
So $x^{2i}(1+x)=x^{2j}(1+x) \Rightarrow x^{2i}=x^{2j}$\
We have already shown that $$x^{2i}=x^{2j}$$ is only true for $i=j$. So
all the sums are unique, and the starter is strong.\
\
Hence, by theorems 2.1 and 2.2, Room squares exist for all $p^n=3($mod
$4)$, and in the case when $p^n=3($mod $4)$ is prime, these Room squares
are based on $Z_p$.\
\
The most generalised case of Mullin & Nemeth’s theorem proves the
existence of Room squares for all prime powers $p^n=2^kt+1$ where $k>1$
and $t>1$ is odd ($k$ and $t$, both positive integers), and reduces to
Theorem 3.4.2 when $k=1$.

#### Theorem 3.4.3 [16]

A strong starter exists in $GF(p^n)$, where $p^n=2^kt+1$ (with $k>1$ and
$t>1$ is odd).\
\
*Proof*\
Let $d=2^{k-1}$\
Then the strong starter in question looks like this: $$ S={

  ---------------------- ------------------------------------- --------------------------------------- ---------------------------------
       $(x^0,x^d)$                 $(x^{2d},x^{3d})$            $ \hspace{0.5cm} ... \hspace{0.5cm} $     $(x^{(2t-2)d},x^{(2t-1)d})$
     $(x^1,x^{d+1})$      $\hspace{0.5cm}(x^{2d+1},x^{3d+1})$   $ \hspace{0.5cm} ... \hspace{0.5cm} $   $(x^{(2t-2)d+1},x^{(2t-1)d+1})$
                                                                $ \hspace{0.5cm} ... \hspace{0.5cm} $  
   $(x^{d-1},x^{2d-1})$   $\hspace{0.5cm}(x^{3d-1},x^{4d-1})$   $ \hspace{0.5cm} ... \hspace{0.5cm} $     $(x^{(2t-1)d-1},x^{2td-1})$
  ---------------------- ------------------------------------- --------------------------------------- ---------------------------------

} $$ Where the pairs have been placed in an array to emphasise that,
when read vertically, this is an exhaustive list of all the non-zero
elements of $GH(p^n)$, ordered according to powers. Of course, in the
$k=1,d=1$ case this starter reduces to the one quoted in Theorem 3.4.2.\
To prove that $S$ is a starter we need also to show, as usual, that the
differences between pairs are all of $GF(p^n)$, and to show that the
starter is strong we need to show that the sums of pairs are all
distinct and non-zero.\
The differences can be written in the following scheme:

  ------------------- -------------------- ------ -------------------------
     $x^0(1-x^d)$,      $x^{2d}(1-x^d)$,    ...,    $x^{(2t-2)d}(1-x^d)$,
     $x^1(1-x^d)$,     $x^{2d+1}(1-x^d)$,   ...,   $x^{(2t-2)d+1}(1-x^d)$,
                                            ...   
   $x^{d-1}(1-x^d)$,   $x^{3d-1}(1-x^d)$,   ...,   $x^{(2t-1)d-1}(1-x^d)$
  ------------------- -------------------- ------ -------------------------

The order of $x$ is $p^n-1=2^kt=2^{k-1}2t=2td > d$, (meaning $x^{2td}=1$
and $x^\alpha \neq 1$ when $1 \leq \alpha < 2dt$) and so $x^d \neq 1$,
so $(1-x^d) \neq 0$.\
We can write the differences in a general form:

$\pm x^{2id+j}(1-x^d) \hspace{0.5cm}$ where
$\hspace{0.5cm} 0 \leq i \leq t-1, \hspace{0.5cm} 0 \leq j \leq d-1$

<span>: l :</span>$\rightarrow$ If there were repetition, either of the
form $D=D$ or $-D=-D$, where $D=x^{2id+j}(1-x^d)$,\
then the following must hold:\
\
Cancelling by $(1-x^d)$, legitimate because $(1-x^d) \neq 0$ gives:\
\
dividing through by $x^{2Id+j}$ leaves\
\
\
But if $i \neq I$, then the LHS has an index which is an integer
multiple of $d$. The index in the RHS,\
however, can never be an integer multiple of $d$ because $J$ and $j$
range over the integers $0...d-1$.\
So the only possibility for equality is when both indices are zero, i.e.
$i=I$ and $j=J$.\

As in the previous proof we have to deal with the possibility of
repetition for differences of opposite sign. For coincidence we require:
$$x^{2id+j}=-x^{2ID+J}$$ $$x^{2id+j}+x^{2Id+J}=0$$ We assume that
$2id+j<2Id+J$ and rewrite this expression as:
$$x^{2id+j}(1+x^{(2I-2i)d+(J-j)})=0$$ Which implies that
$x^{(2I-2i)d+(J-j)}=-1$\
But in $GF(q),x^{\frac{1}{2}(q-1)}=-1$. Where, in this case $q-1=2^kt$,
so $\frac{1}{2}(q-1)=2^{k-1}t=dt$. $$\therefore x^{dt} = -1$$
$$\Rightarrow (2I-2i)d+(J-j)=dt$$

$\Rightarrow (J-j)$ is an integer multiple of $d$ or zero.

But $J$ and $j$ both take only the values $0...d-1$, so $(J-j)$ is in
the interval $[1-d,d-1]$ and hence must be zero, leaving $$(2I-2i)d=dt$$
$$2I-2i=t$$ But $t$ is strictly odd, and so we have reached a
contradiction, hence the differences are all unique, belong to $GF(p^n)$
and there are $2td$ of them, hence each member of $GF(p^n)$ occurs
exactly once as a difference. So $S$ is a starter.\
To prove that the starter is strong we write the sums as

  ------------------- -------------------- ------ -------------------------
     $x^0(1-x^d)$,      $x^{2d}(1-x^d)$,    ...,    $x^{(2t-2)d}(1-x^d)$,
     $x^1(1-x^d)$,     $x^{2d+1}(1-x^d)$,   ...,   $x^{(2t-2)d+1}(1-x^d)$,
                                            ...   
   $x^{d-1}(1-x^d)$,   $x^{3d-1}(1-x^d)$,   ...,   $x^{(2t-1)d-1}(1-x^d)$
  ------------------- -------------------- ------ -------------------------

and notice that $x^d=-1 \Rightarrow d=dt$ (because
$x^{dt}=-1) \Rightarrow t=1$, but instead we insisted that $t$ be
strictly greater than one (this being the reason why). So
$(1+x^d) \neq 0$ and the above argument (denoted by $\rightarrow$)
involving $(1-x^d)$ can be invoked, replacing $(1-x^d)$ by $(1+x^d)$. So
$S$ is a strong starter, and the general theorem of Mullin & Nemeth is
proven, guaranteeing the existence of a vast class of Room Squares.

The Trouble with Fermat Numbers
-------------------------------

Unfortunately, in establishing the Mullin & Nemeth starters we were
forced to exclude a similarly vast, potentially infinite, class of Room
squares by insisting that $t$ be strictly greater than one. These
exceptional Room squares have side $2^k+1$.\
\
Rectifying this problem is essential if we are to prove the existence of
Room squares. As mentioned previously, the proof relies on a
multiplication theorem, so proving that all the ’prime’ Room squares
exist is vital. Although the theorem of Mullin & Nemeth will take care
of all squares with prime power side, the multiplication theorem is
necessary for proving the existence of those whose side can be
decomposed into prime factors different from each other. In fact, the
multiplication theorem means that we can ignore the Mullin & Nemeth
construction except in the prime case, resorting to multiplication to
recover the prime power squares. Similarly we are only concerned with
recovering the exceptional squares with side $2^k+1$, when $2^k+1$ is
prime.\
\
Primes of this form are known as **Fermat Numbers** or **Fermat
Primes**, after Pierre de Fermat who, 360 years ago conjectured that
numbers of the form $2^k+1$ are always prime when $k$ is a power of two.

  ----------------------
  $F_m=2^{2^m}+1$
  $F_0=2^1+1=3$
  $F_1=2^2+1=5$
  $F_2=2^4+1=17$
  $F_3=2^8+1=257$
  $F_4=2^{16}+1=65537$
  ----------------------

After the first four of Fermat’s numbers, all of which were known to him
to be prime. Nearly one hundred years later Euler calculated the
following, $$F_5 = 2^{32}+1=4294967297=641\times 6700417$$ and in doing
so disproved Fermat’s conjecture.\
\
Since Euler’s time, $F_6$, $F_7$ and $F_8$ have all been factorised[^6]
. It is also known, although most of the factorisations remain unknown,
that $F_m$ is composite for $m=[9...23]$. $F_{24}$, a number with over 5
million digits, remains in doubt.\
\
Whether there be an infinite number of Fermat primes or whether, as
empirically seems to be the case, there are only finitely many (possibly
just five) such primes, in order for the proof of the existence of Room
squares for all odd side greater than 7 to be complete these Fermat
prime Room squares must be included.\
\
When the problem of Fermat Room squares was tackled first in the early
1970s, W.D.Wallis used a Theorem of J.D.Horton’s which adapted a famous
result of E.H.Moore’s from the theory of Steiner triple systems.\
\
Moore, in 1893, was able to prove that if Steiner triple systems of
orders $v_1$, $v_2$ and $v_3$ exist, where the $v_2$ system is a
sub-system of the $v_3$ system, then an STS of order $v_1(v_2-v_3)+v_3$
also exists. Horton[12] adapted this result to other combinatorial
objects including Room squares and Wallis[25] was able to use this
Moore-type construction method to include all of the Fermat primes,
except $F_3=257$[^7] .\
\
*Example 3.5.1*\
If Room squares with side $v_1$, $v_2$ and $v_3$ exist, where the square
of side $v_2$ is a subsquare of the square with side $v_3$, then a Room
square of side $F_4=65537$ exists. Room squares of side 7 and 11 exist,
according to the theory of Mullin & Nemeth. Applying Horton’s theorem
once, with $v_3=0$ gives a new square of side $v_1v_2=77$ (note that
Horton’s theorem reduces to the multiplication theorem when $v_3=0$).\
\
The trivial Room square of side one exists, and the Mullin & Nemeth
starters will provide a Room square of size 13. So we can apply Horton’s
theorem once again to gain a Room square of side 989 because:
$$989=13(77-1)+1$$ Finally we can use Mullin & Nemeth to produce a Room
square of side 67, and a final application of Horton’s theorem gives:
$$65537=67(989-11)+11$$ The proof of Horton’s theorem and also an
explanation of Wallis’s application of that theorem to solving the
Fermat prime problem is excluded because another solution was
subsequently found. A year after Wallis had published his solution to
the Fermat problem, Chong and Chan published their (independent)
discovery of the strong starters which are known as the Mullin & Nemeth
starters. Also included in their paper was an alternative solution to
the same problem, but their solution continued to involve the
starter-adder method. This theorem we prove instead.

#### Theorem 3.5.1 [6]

\
For every Galois field of order $(2^{2^m}+1)$, where $m \geq 2$, there
exists a Room square of order $(2^{2^m}+2)$.\
\
*Proof*\
The following pairs in $Z_p$ (where $p=2^{2^d}+1$ and $d=2^{m-1})$
constitute a strong starter.

1.  $\{i+(r-1)2^d,i2^d-(r-1\}$

2.  $\{(2^d-i)2^d+r,(2^{d-1}-r)2^d+2^{d-1}-i+1\}$

3.  $\{2^{d-1}+r-1)2^d+2^{d-1}+i,(2^{d-1}+i-1)2^d+2^{d-1}-(r-1)\}$

4.  $\{(2^{d-1}-i)2^d+2^{d-1}+r,(2^d-r+1)2^d-i+1\}$

Where $1 \leq r \leq 2^{d-2}$ and $1 \leq i \leq 2^{d-1}$, so rather
than just 4 pairs there are $4 \cdot 2^{d-2} \cdot 2^{d-1}=2^{2d-1}$
pairs arranged in four different classes. Before completing the proof we
pause for an example just to illustrate the real simplicity of these
apparently complicated pairs.\
\
*Example 3.5.2*\
Suppose $p=2^{2\cdot 2}+1=17=F_2$, then $d=2^1 \Rightarrow m=2$\
$r=1,1 \leq i \leq 2$ and the following pairs should be a strong
starter.\

<span>-1.15cm</span>

      $i=1,r=1$                                         $i=2,r=1$
  --- ------------------------------------------------- -------------------------------------------------
  1   $\{1+0 \cdot 2^2,1 \cdot 2^2 - 0\} = \{1,4\}$     $\{2+0 \cdot 2^2,2 \cdot 2^2 -0\} = \{2,8\}$
  2   $\{(2^2-1)2^2+1,(2^1-1)2^2+2^1-1+1\}=\{13,6\}$    $\{(2^2-2)2^2+1,(2^1-1)2^2+2^1-2+1\}=\{9,5\}$
  3   $\{(2^1+1-1)2^2+2^1+1,(2^1+1-1)2^2+2^1-(1-1)\}$   $\{(2^1+1-1)2^2+2^1+2,(2^1+2-1)2^2+2^1-(1-1)\}$
      $=\{11,10\}$                                      $=\{12,14\}$
  4   $\{(2^1-1)2^2+2^1+1,(2^2-1+1)2^2-1+1\}$           $\{(2^1-2)2^2+2^1+1,(2^2-1+1)2^2-2+1\}$
      $=\{7,16\}$                                       $=\{3,15\}$

**Table 4**

The pairs generated by this method contain each non-zero member of
$Z_{17}$ exactly once in their union satisfying the first property of a
starter.\
The differences are
$\{\pm 3,\pm 7,\pm 1,\pm 8, \pm 6, \pm 4, \pm 2, \pm 5\}=Z_{17} \backslash \{0\}$,
satisfying the other necessary property of a starter.\
The sums 5,2,4,6,10,14,9,1 are all unique, hence the starter is strong
and the set\
$\{-5,-2,-4,-6,-10,-14,-9,-1\}=\{12,15,13,11,3,8,16\}$ is an adder. So
the following first row will generate a Room square under cyclic
construction:

   $\infty,0$   3,15   13,6   -   11,10   1,4   7,16   -   -   12,14   2,8   -   -   -   9,5   -   -
  ------------ ------ ------ --- ------- ----- ------ --- --- ------- ----- --- --- --- ----- --- ---

In order to prove that the pairs $1...4$ are a strong starter from any
$Z_p$ we need to prove the following:

1.  The union of all the pairs contains each non-zero member of $Z_p$
    exactly once.

2.  The differences are all the non-zero members of $Z_p$ exactly once.

3.  The sums are all distinct and non-zero.

This is a formidable task, one that would take many pages to prove in
full detail. So instead we sketch an outline of the proof, explicitly
proving a few specific cases.\
\
First we prove (a) completely.\
The non-zero members of $Z_P$, namely $\{1...2^{2d}\}$, can be
represented uniquely by:
$$C(u,v) = u2^d+v \hspace{0.5cm} \mathrm{where} \hspace{0.5cm} 1 \leq v \leq 2^d
\hspace{0.25cm} \mathrm{and} \hspace{0.25cm} 0 \leq u \leq 2^d-1$$
*Proof*\
Indeed if $$u_12^d+v_1=u_22^d+v_2$$ then $$(u_1-u_2)2^d=(v_2-v_1)$$ The
RHS takes integer values in the interval $[-(2^d-1),2^d-1]$, which is
symmetric about the origin and smaller than $2^d$ on both sides. Whereas
the LHS takes integer multiple steps of size $2^d$, so the equality can
only hold in the case when both sides equal zero. Which implies
$u_1=u_2$, $v_1=v_2$ and $C(u,v)$ is unique representation the non-zero
members of $Z_p$. $u$ takes $2^d$ values and $v$ takes $2^d$ values so
there are $2^{2d}$ unique non-zero members of $Z_p$ represented in this
way, so each member of $Z_p$ is represented.\
The left and right hand members of each pair can be characterised by a
range of values of $u$ and $v$ in the following manner.\
Take, for instance, the left hand member of pair 1. $$i+(r-1)2^d$$ Here
$v=i$ and so $1 \leq v \leq 2^{d-1}$, while $u=(r-1)$, so
$0 \leq u \leq 2^{d-2}-1$. The full list of intervals for each member of
each pair is tabulated below.

  ------ -------- ------------------------------- --------------------------------
   Pair   Member                $u$                             $V$
    1.      L             $[0,2^{d-2}-1]$                  $[1,2^{d-1}]$
            R             $[0,2^{d-1}-1]$           $[3 \cdot 2^{d-2}+1,2^{d}]$
    2.      L           $[2^{d-1},2^{d}-1]$                $[1,2^{d-2}]$
            R          $[2^{d-2},2^{d-1}-1]$               $[1,2^{d-1}]$
    3.      L      $[2^{d-1},3 \cdot 2^{d-2}-1]$        $[1+2^{d-1},2^{d}]$
            R           $[2^{d-1},2^{d}-1]$            $[1+ 2^{d-2},2^{d-1}]$
    4.      L             $[0,2^{d-1}-1]$          $[1+ 2^{d-1},3 \cdot 2^{d-2}]$
            R       $[3 \cdot 2^{d-2},2^{d}-1]$         $[1+2^{d-1},2^{d}]$
  ------ -------- ------------------------------- --------------------------------

**Table 5**

It was mentioned earlier that there were $2^{2d-1}$ pairs, each of which
has two members, so there are $2^{2d}$ elements altogether in the pairs
of the starter, which is the same as the number of elements in $Z_p$.
Because $C(u,v)$ is a unique representation for each member of $Z_p$,
for an element of $Z_p$ to occur more than once in the starter requires
repetition of both $u$ and $v$. This cannot happen because when two
intervals overlap (as they do in the values of $v$ for 1L and 2R).\
\
To prove (b) we need to show that the differences between two pairs of
type 1 are all unique, similarly between two pairs of types 2,3 and 4.
Moreover we need to show that there can be no repetition in differences
between a pair of type 1 and a pair of type 2, also type 1 with types 3
in 4. Similarly for 2,3 and 4. All together there are ten cases to
prove, tabulated below, where a pair of numbers represents the two types
of pairs from the starter.

  (i)       11  (ii)    12  (iii)    13  (iv)    14
  -------- ---- ------ ---- ------- ---- ------ ----
  (v)       22  (vi)    23  (vii)    24         
  (viii)    33  (ix)    34                      
  (x)       44                                  

**Table 6**

To illustrate, we prove (v), in other words that differences ebtween two
different pairs, both of type 2 are always unique.\
Type 2 have the form: $\{(2^d-i)2^d+r, (2^{d-1}-r)2^d+2^{d-1}-i+1\}$.
Therefore, a difference between the elements of a pair of type 2 has the
form: $$\pm \{(2^d-i)2^d+r-(2^{d-1}-r)2^d-2^{d-1}+i-1\}$$ If two
different pairs had the same difference we could write:
$$(2^d-i)2^d+r-(2^{d-1}-r)2^d-2^{d-1}+i-1
\equiv \pm \{(2^d-j)2^d +s-(2^{d-1}-s)2^d-2^{d-1}+j-1\}(\mathrm{mod} \hspace{0.1cm} p)$$
for some $i \neq j, r \neq s$. There are two cases to prove, firstly
consider the one involving the + sign.
$$(2^d-i)2^d+r-(2^{d-1}-r)2^d-2^{d-1}+i-1 \equiv (2^d-j)2^d + s -(2^{d-1}-s)2^d - 2^{d-1} + j -1 (\mathrm{mod} \hspace{0.1cm} p)$$
$$\cancel{(2^d}-i)2^d+r-(\cancel{2^{d-1}}-r)2^d-\cancel{2^{d-1}}+i\cancel{-1} \equiv \cancel{(2^d}-j)2^d + s -(\cancel{2^{d-1}}-s)2^d - \cancel{2^{d-1}} + j \cancel{-1} (\mathrm{mod} \hspace{0.1cm} p)$$
In this case we have been helped out with some very convenient
cancelling, leaving just:
$$-i2^d+r+r \cdot 2^d + i \equiv -j \cdot 2^d + s + s \cdot 2^d + j \hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(-i+j)2^d + i -j \equiv (s-r)(1+2^d) \hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(j-i)(2^d -1) \equiv (s-r)(1+2^d) \hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$\times (2^d+1)$
$$(j-i)(2^{2d} -1) \equiv (s-r)(1+2 \cdot 2^d + 2^{2d}) \hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$2^{2d}+1=p$ $\hspace{0.5cm}\therefore$ $2^{2d}-1 \equiv -2$ (mod $p$)
$$-2(j-i)\equiv (s-r)2 \cdot 2^d \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(i-j)\equiv (s-r) 2^d \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p) \hspace{2cm} ...(\mathrm{A})$$
$1 \leq i, j \leq 2^{d-1}$\
$\therefore (i-j)$ lies in the interval $[-(2^{d-1}-1),2^{d-1}-1]$,
which is symmetric about the origin, with length
$2 \cdot 2^{d-1}-2=2^d-2 < p = 2^{2d}+1$.\
$1 \leq s,r \leq 2^{d-2}$\
$\therefore(s-r)2^d$ lies in the interval
$[-(2^{d-2}-1)2^d,(2^{d-2}-1)2^d]$, again symmetric about the origin
with length $2^{2d}-2^{d+1} < p$.\
So for A to hold requires that $$(i-j)=(s-r)2^d$$ But the LHS has an
interval with length $2^d-2 < 2^d$ whereas the RHS is some positive or
negative integer multiple of $2^d$, so the two could only be equal when
$i=j,r=s$ contradicting the original hypothesis.\
\
There is still the negative case to deal with:
$$(2^d-i)2^d+r-(2^{d-1}-r)2^d-2^{d-1}+i-1 \equiv
-(2^d-j)2^d-s+(2^{d-1}-s)2^d+2^{d-1}-j+1\hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(2^d-i)2^d-(2^{d}-j)2^d+i+j \equiv
-s+(2^{d-1}-s)2^d + (2^{d-1} -r)2^d -r + 2 \cdot 2^{d-1} + 2 \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$2 \cdot 2^{2d} + (1-2^{d})(i+j) \equiv
-(s+r)(1+2^d)+2^{2d}+1+2^d+1 \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$2^{2d}+1=p \therefore 2^{2d} \equiv -1 \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$
$$-2+(1-2^d)(i+j) \equiv -(s+r)(1+2^d)+1+2^d \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(1-2^d)(i+j) \equiv -(s+r)(1+2^d)+3+2^d \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
Now multiply throughout by $(1+2^d)$, noting that:\
$(1+2^d)(1-2^d) \equiv 2(\hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p),(1+2^d)(1+2^d)
=1+2 \cdot 2^d + 2^{2d} \equiv 2^{d+1}\hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$\
and
$(1+2^d)(3+2^d)=3+4 \cdot 2^d+2^{2d} \equiv 2^{d+2}+2 \hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$\
$$2(i+j)\equiv -2^{d+1}(s+r)+2^{d+2}+2\hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(i+j)\equiv -2^{d}(s+r)+2^{d+1}+1\hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$2^d(s+r)\equiv 2 \cdot 2^{d}-(i+j)+1\hspace{0.1cm} (\mathrm{mod} \hspace{0.1cm} p) \hspace{1cm}... (\mathrm{B})$$
$1 \leq s, r \leq 2^{d-2}$\
$\therefore 2 \cdot 2^d \leq 2^d(s+r) \leq 2^d2^{d-1}$\
The LHS lies in the interval $[2^{d+1},2^{2d-1}]$, which itself is
located somewhere in the interval $[0,p]$.\
$1 \leq i, j \leq 2^{d-1}$\
$\therefore 2 \leq i + j \leq 2^d$\
$2^d \leq 2 \cdot 2^d -(i+j) \leq 2^{d+1} - 2$\
So the RHS lies in the interval $[2^d+1,2^{d+1}-1]$, again this is
located with $[0,p]$.\
So for B to be satisfied requires that $$2^d(s+r)=2 \cdot 2^d-(i+j)+1$$
But the RHS and LHS intervals are disjoint so this can never happen.\
So the absence of repetition in the differences of two different pairs
both of type 2 is proven. All cases involving different pairs of the
same type are proven in this way {cases (i),(v),(viii),(x)}.\
\
Finally we demonstrate how the other 6 cases are proven, those involving
pairs of different types.\
Inevitably the approach is very similar.\
\
Consider a pair of type 1 and another pair of type 4 (case iv). If there
were a repetition of differences between pairs of this type we could
write:
$$i+(r-1)2^d-i2^d+(r-1) \equiv \pm \{(2^{d-1}-j)2^d+2^{d-1}+s-(2^d-s+1)2^d+j-1\}
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$ Consider the + sign,
then
$$i-i2^d-(2^{d-1}-j)2^d-j \equiv -(r-1)2^d-(r-1)+s-(2^d-s+1)2^d+2^{d-1}-1
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(1-2^d)(i-j)-2^{2d-1} \equiv -(2^d+1)(r-s)-2^{2d}+2^{d-1}
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$2^{2d} \equiv -1\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$\
$$(1-2d)(i-j) \equiv -(2^d+1)(r-s)+2^{d-1} + 2^{2d-1} + 1
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$ $\times 2$\
 $$2(1-2d)(i-j) \equiv -2(2^d+1)(r-s)+2^{d} + 2^{2d} + 2
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$2(1-2d)(i-j) \equiv -2(2^d+1)(r-s)+2^{d}+1
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$ $\times(2^d+1)$\
 $$4(i-j) \equiv -2 \cdot 2^{d+1}(r-s)+2^{d+1}
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$(i-j) \equiv -2^{d}(r-s)+2^{d-1}
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$
$$2^d(r-s) \equiv 2^{d-1}-(i-j)
\hspace{0.3cm} (\mathrm{mod} \hspace{0.1cm} p)$$ In this instance the
LHS has interval $[2^d-2^{2d-2},2^{2d-2}-2^d]$. while the interval of
the RHS is $[1,2^d-1]$. Both are smaller than $p$ in length, so for
equality requires $$2^d(r-s) = 2^{d-1}-(i-j)$$ But this can never be
true because the left side is always either zero or an integer multiple
of $2^d$, whereas the interval of the right is $[1,2^d-1]$.\
\
All other cases are dealt with in a very similar manner, and the proof
of (c), namely that all sums are unique, is not very different.

A Multiplication Theorem
------------------------

Having a theorem which enables new Room squares to be composed from old
Room squares is of vital importance to the proof of the existence of
Room squares. With such a theorem, in conjunction with the Mullin-Nemeth
starters, we will be able to construct Room squares of almost any order.
The exceptions will be due to the non-existence of orders 4 and 6. The
multiplication theorem that will be proven is:

#### Theorem 3.6.1

\
*If Room squares of side m and side n exist then a Room square of side
mn also exists.*\
\
This theorem was proposed initially in [5] but later a counter-example
to this method was found [15]. The proof here is based upon [1], which
in turn is based upon the proof in [22].\
\
*Proof*\
$M$ and $N$ are two Room squares. $M$ is of side $m$ and based on
$\{0,1,2,...,m\}$, while $N$ is of side $n$ and based on
$\{0,1,2,...,n\}$.\
\
The join of two Latin squares $A$ and $B$ is the array whose
$(i,j)^{\mathrm{th}}$ entry contains the ordered pair formed from the
$(i,j)^{\mathrm{th}}$ entry of $A$ taking the left position and the
$(i,j)^{\mathrm{th}}$ entry of $B$ taking the right. If the join of two
Latin squares contains $n^2$ unique ordered pairs, the two Latin squares
$A$ and $B$ are said to be orthogonal.\
\
$L_1$ and $L_2$ are two mutually Latin squares (MOLS) based on
$\{1,2,3,...,n\}$.\
We construct the new Room square $R=MN$ by replacing each element of $M$
by an $n \times n$ array according to the following flow diagram where
$(i,j)$ is a pair from $M$.

**Figure 19**

This procedure has replaced each pair in $m$ by an $n \times n$ array,
resulting in an $mn \times mn$ array. This array is based upon
$\{0,n+1,n+2,...,n+mn\}$, and we now prove that it has the properties of
a Room square, namely:

1.  Each element of the array is either empty or contains an unordered
    pair.

2.  Each row and column contains each of $\{0,n+1,n+2,...,n+mn\}$
    exactly once.

3.  Each pair from $\{0,n+1,n+2,...,n+mn\}$ occurs exactly once in the
    array.

The first property is easily satisfied. The procedure followed did
nothing but replace empty elements and unordered pairs with arrays
containing nothing more than empty elements or pairs.\
\
The second is similarly straightforward. Consider an arbitrary row of
the new square $R$, call it $i$. This row arose from applying
prescriptions (i),(ii), and (iii) to some row of $M$. This row of $M$
contained the elements $0...m$ exactly once. One of these elements, call
it $a$, was paired with 0. So in $i$ from (ii) occur the numbers
$(0;1+an...m+an)$ exactly once. In the join of two MOLS the numbers
$1...n$ occur twice per row, once in $L_1$ once in $L_2$. These are
replaced by $(1+un...n+un)$ and $(1+vn...n+vn)$ as $u$ and $v$ take on
all values $1,2,...,m$ excluding\
Together these two prescriptions produce the elements
$$\{0;1+n,2+n,...,n+mn\}$$ exactly once per row and column.\
\
To prove condition 3 is true we show that $R$ contains the correct
number of pairs and that\
these pairs are distinct. Because we have shown 2 to be correct these
pairs must be the right\
Any Room square, of side $n$, contains $\frac{1}{2}(n+1)$ pairs per row,
therefore $\frac{1}{2}n(n+1)$ pairs over\
Room square of side $mn$ ought to contain $\frac{1}{2}mn(mn+1)$ pairs.\
In $M$ there were $m$ instances of $\{0,k\}$, each of these was replaced
by a Room square of side\
$\frac{1}{2}n(n+1) \cdot m$ pairs were contributed by (ii) to $R$.\
In $M$ there were $\frac{1}{2}(m+1)-1 = \frac{1}{2} (m-1)$ pairs per row
of the form $\{u,v\}$, therefore $\frac{1}{2}m(m$\
of these pairs throughout $M$. These were replaced by MOLS of side $n$,
containing $n^2$ pairs\
each. So $\frac{1}{2}m(m-1) \cdot n^2$ pairs were contributed to $R$
from (iii).\
(i) contributed no pairs to $R$.
$$\frac{1}{2} mn (n+1) + \frac{1}{2}m(m-1)n^2$$
$$=\frac{1}{2}mn\{(n+1)+n(m-1)\}$$ $$=\frac{1}{2}mn(mn+1)$$ So the
number of pairs in $R$ is correct.\
\
To show that all the pairs are distinct consider $P(i,j)$ which
represents those pairs generated\
from the element $(i,j)$ of $M$. The pairs within $P(i,j)$ are always
distinct because they are\
the pairs in a Room square or a join of 2 MOLS.\
\
However we also need to show that $P(i,j)$ and $P(h,k)$ have no pairs in
common when $i,j \neq h,k$. There are 3 cases to consider. Both sets of
pairs are chosen from the join of 2 M\
both sets are from Room squares, or one set from each.\
\
If both sets of pairs were generated from the join of two MOLS then the
pairs have the form$$\{un+l_1,vn+l_2\}$$ If this pair occurs in both
$P(i,j)$ and $P(h,k)$ then $(l_1,l_2)$ occurs in two different places
in\
joins of two MOLS which is a contradiction.\
\
The case where both sets of pairs are generated by Room squares is
easily dealt with, because\
the Room squares used to construct $R$ are based on different sets, so
two could never contain\
same pair.

Summary
-------

So far we have shown that all Room squares whose side can be expressed
as a prime power\
$p^n=2^kt+1$ can be constructed by using the Mullin-Nemeth starters. The
Fermat Primes\
shown to be an exception to the Mullin-Nemeth construction, but this was
overcome by\
introducing the theorem of Chong and Chan which provides a strong
starter form all Room squares of side $(2^{2^m}+1)$, encompassing the
Fermat primes. So we have proven that all Room squares exist whose side
is a prime number, other than 3 or 5. The multiplication theorem\
enables us to state that all Room squares exist whose side can be
factored as $p_1p_2p_3...p_n$\
$p_i \geq 7$.\
\
The non-existence of Room squares with sides 3 and 5, prevents us from
constructing those\
squares whose sides have a factor of 3 or 5. Within this class of exempt
Room squares the Mullin & Nemeth starters will take care of the prime
power sides. But for those whose side is not a prime power a final
theorem, due to W.D. Wallis is needed to complete the proof.

n-tuplication of Room squares
-----------------------------

#### Theorem 3.8.1[25]

\
If $r$ and $n$ are odd integers such that $r \geq n$, and if there is a
Room square $R$ of side $r$, then there is a Room square of side $rn$.\
\
*Example 3.8.1*\
Before proving this theorem, we look at an example of triplication in
order to introduce thisfairly complicated construction.\
The approach taken is to take a Room square of side 7, create 9 arrays
very similar in structure tothis Room square, and then arrange these 9
arrays into a 21x21 side array which is very\
Room square.\
Suppose we wished to triplicate the following Room square.

   $\infty 0$       -            -            25           -            16           34
  ------------ ------------ ------------ ------------ ------------ ------------ ------------
       45       $\infty 1$       -            -            36           -            20
       31           56       $\infty 2$       -            -            40           -
       -            42           60       $\infty 3$       -            -            51
       62           -            53           01       $\infty 4$       -            -
       -            03           -            64           12       $\infty 5$       -
       -            -            14           -            05           23       $\infty 6$

**Figure 20**

Unfortunately, this row has simply too many elements. There should be
only 11 pairs, not\
and the new Room-ish square would be based on a set of 24 elements not
22 as we require.Wallis’s original idea had been to somehow merge the
three $\infty _\mathrm{i}$ into one element, but he eventually decided
instead to go back to the original square and strip out the diagonal
elements.Building a Room square is then a matter of arranging the
following arrays, sometimes called frames,

$R_{ij} = $

                                                                                          $2_\mathrm{i}5_\mathrm{j}$                                $1_\mathrm{i}6_\mathrm{j}$   $3_\mathrm{i}4_\mathrm{j}$
  ---------------------------- ---------------------------- ---------------------------- ---------------------------- ---------------------------- ---------------------------- ----------------------------
   $4_\mathrm{i}5_\mathrm{j}$                                                                                          $3_\mathrm{i}6_\mathrm{j}$                                $2_\mathrm{i}0_\mathrm{j}$
   $3_\mathrm{i}1_\mathrm{j}$   $5_\mathrm{i}6_\mathrm{j}$                                                                                          $4_\mathrm{i}0_\mathrm{j}$  
                                $4_\mathrm{i}2_\mathrm{j}$   $6_\mathrm{i}0_\mathrm{j}$                                                                                          $5_\mathrm{i}1_\mathrm{j}$
   $6_\mathrm{i}2_\mathrm{j}$                                $5_\mathrm{i}3_\mathrm{j}$   $0_\mathrm{i}1_\mathrm{j}$                                                            
                                $0_\mathrm{i}3_\mathrm{j}$                                $6_\mathrm{i}4_\mathrm{j}$   $1_\mathrm{i}2_\mathrm{j}$                               
                                                             $1_\mathrm{i}4_\mathrm{j}$                                $0_\mathrm{i}5_\mathrm{j}$   $2_\mathrm{i}3_\mathrm{j}$  

**Figure 21**

into a 21x21 array, and subsequently finding some way to fill in the
missing two pairs from\
row of the new square, with the aim of producing a Room square based on
$$S = \{\infty,0_1,1_1,...,6_1,0_2,1_2,...,6_2,0_3,1_3,...,6_3\}$$
Inevitably this approach leads to new problems.\
\
Firstly consider how to arrange the frames appropriately. Suppose we put
$R_{12}$ next to $R_{13}$,\
the left hand members of pairs in each row of $R_{12}$ will be repeated
in the same row of the\
21x21 square due to the placing of $R_{13}$. The same would be true for
any $R_{ij}$ next to any $R_{ik}$,\
next to $R_{kj}$. So for that reason, in the super-array of $R_{ij}$s we
require in each super-row that\
each value 1,2 and 3 and similarly that $j$ takes on all these values.
To satisfy the column\
for our new Room square we also require that no $R_{ij}$ occurs above or
below an $R_{ik}$ or $R_{kj}$, and\
that reason we must also insist that for any super-column of $R_{ij}$s,
$i$ and $j$ independently\
values 1..3, so that each member of $S \backslash \{\infty\}$ occurs
once in the corresponding 7 columns of\
finished Room square – (except for the missing
$\{x_i: 0 \leq x \leq 6\}$ from all columns $x_i$).\
\
Furthermore, as we are aiming for an array in which all the unordered
pairs from $S$ occur\
once if we also insist that each value of $i$ is paired with each value
of $j$ exactly once in\
super-array then we should obtain most of these pairs. In fact, because
$R_{ij} \cup R_{ji}$ contains\
unordered pairs from $\{9_i,o_j,1_i,1_j,...,6_i,6_j\}$, except those of
the form $\{x_i,x_j\}$ $1 \leq i,j \leq 3$\
shall obtain all the unordered pairs of $S$ except those of the form
$$\{\infty,x_1\},\{\infty,x_2\},\{\infty,x_3\},\{x_1,x_2\},\{x_1,x_3\},\{x_2,x_3\}, 0 \leq x \leq 6$$\
The ideal solution to this problem (because it solves the problem of
missing pairs as well as completing rows/columns) would be to place
pairs of the form $\{\infty, x_j\}$ and $\{x_i, x_j\}$ at the
intersection of rows $x_j$ and column $x_j$, but of course this
intersection is a single box, and we don’t want two pairs in one box.
Wallis’s solution to this problem was to permute the columns of some of
the $R_{ij}$s from one super-column of the array of frames with the
intention of arranging it so that the elements $x_i$ $x_j$ would be
vacant from some column $y \neq x_j$. This enables us to put the
$\{\infty, x_j\}$ in column $x_j$ and the $\{x_i,x_j\}$ in column $y$.\
\
*Example,*\
The elements missing from row $0_1,$ $ \infty, 0_1, 0_2, 0_3$, are also
missing from column $0_1$ (due to the removal of the pair $\{\infty,0\}$
from the original Room square to create the frame). There is no problem
in putting $\{\infty,0_1\}$ in position $(0_1,0_1)$, but if we want to
put $\{0_2,0_3\}$ in row $0_1$ it must go in some other column of block
$R_{11}$, while remaining in column $1_1$ of blocks $R_{23}$ and
$R_{32}$, this can be achieved through a column permutation applied only
to $R_{23}$ and $R_{32}$.\
\
Notice that it would be of little use to swap columns $0_1$ and $4_1$ of
blocks $R_{23}$ and $R_{32}$, as the fourth column is occupied already
in the first row of block $R_{11}$. But we could swap $0_1$ with any of
$1_1,2_1,3_1$ or $5_1$ because all these columns are empty in row $0_1$.
Clearly the essential property we require of any column permutation that
we decide to use, call it $\theta$, is that $(x,x\theta)$ is unoccupied
in the original Room square.

#### Lemma 3.8.1

\
Given a Room square $R$ of side $r$, where $r=2s+1$, there are $s$
permutations $\phi_1,\phi_2,...,\phi_s$ of $\{1,2,...,r\}$ with the
properties that $k\phi_i=k\phi_j$ never occurs unless $i=j$, and that
cell $(k,k\phi_i)$ is empty for $1 \leq k \leq r, 1 \leq i\leq s$.\
\
*Proof*\
We define a matrix $M$ in the following manner:\
If position $(k,l)$ is *empty* in $R$ then the $(k,l)$ position of $M$
is 1, otherwise it is 0.\
Because $M$ is a matrix of 0s and 1s, whose every row and column sum is
equal to $s$, it can be decomposed into $s$ matrices, each of which
having exactly one 1 in each row and column[^8]. $$M=P_1+P_2+...+P_s$$
These matrices ,when interpreted in the following or similar manner, are
known as\
**permutation matrices**:\
Define $\phi_i$ as the permutation corresponding to matrix $P_i$ such
that if $(k,l)$ is 1 in $P_i$ then $k\phi _i=l$.\
The definition of $M$ ensures that the $(k,k\phi _i)$, so $M$ would have
an entry equal to 2 or more, contradicting the definition.\
\
*Example* cont...,\
The matrix $M$ associated with the square from Figure 19 is:

$$\begin{gathered}
M=
  \begin{bmatrix}
  0 & 1 & 1 & 0 & 1 & 0 & 0\\
  0 & 0 & 1 & 1 & 0 & 1 & 0\\
  0 & 0 & 0 & 1 & 1 & 0 & 1\\
  1 & 0 & 0 & 0 & 1 & 1 & 0\\
  0 & 1 & 0 & 0 & 0 & 1 & 1\\
  1 & 0 & 1 & 0 & 0 & 0 & 1\\
  1 & 1 & 0 & 1 & 0 & 0 & 0\\
  \end{bmatrix}\end{gathered}$$

\
Which can be decomposed (not uniquely) into these permutation matrices:

$$\begin{gathered}
M= P_1 + P_2 + P_3 = 
  \begin{bmatrix}
  0 & 1 & 0 & 0 & 0 & 0 & 0\\
  0 & 0 & 1 & 0 & 0 & 0 & 0\\
  0 & 0 & 0 & 0 & 1 & 0 & 0\\
  1 & 0 & 0 & 0 & 0 & 0 & 0\\
  0 & 0 & 0 & 0 & 0 & 1 & 0\\
  0 & 0 & 0 & 0 & 0 & 0 & 1\\
  0 & 0 & 0 & 1 & 0 & 0 & 0\\
  \end{bmatrix}
  +
  \begin{bmatrix}
  0 & 0 & 0 & 0 & 1 & 0 & 0\\
  0 & 0 & 0 & 1 & 0 & 0 & 0\\
  0 & 0 & 0 & 0 & 0 & 0 & 1\\
  0 & 0 & 0 & 0 & 0 & 1 & 0\\
  0 & 1 & 0 & 0 & 0 & 0 & 0\\
  0 & 0 & 1 & 0 & 0 & 0 & 0\\
  1 & 0 & 0 & 0 & 0 & 0 & 0\\
  \end{bmatrix}
  +
  \begin{bmatrix}
  0 & 0 & 1 & 0 & 0 & 0 & 0\\
  0 & 0 & 0 & 0 & 0 & 1 & 0\\
  0 & 0 & 0 & 1 & 0 & 0 & 0\\
  0 & 0 & 0 & 0 & 1 & 0 & 0\\
  0 & 0 & 0 & 0 & 0 & 0 & 1\\
  1 & 0 & 0 & 0 & 0 & 0 & 0\\
  0 & 1 & 0 & 0 & 0 & 0 & 0\\
  \end{bmatrix}\end{gathered}$$

\
The permutations associated with these matrices are, in cycle notation:
$$\phi _1 = (1235674), \phi _2 = (1524637), \phi _3 = (1345726)$$ If we
choose to apply $\phi _1$ to the columns of blocks $R_{23}$ and $R{32}$
we get:

<span>|c|c|c|c|c|c|c|c|</span>

  ------
   Col/
   Row
  ------

& $0_1$ & $1_1$ & $2_1$ & $3_1$ & $4_1$ & $5_1$ & $6_1$\
$0_1$ & & & & $2_15_1$ & & $1_16_1$ & $3_14_1$\
$1_1$ & $4_15_1$ & & & & $3_16_1$ & & $2_10_1$\
$2_1$ & $3_11_1$ & $5_16_1$ & & & & $4_10_1$ &\
$3_1$ & & $4_12_1$ & $6_10_1$ & & & & $5_11_1$\
$4_1$ & $6_12_1$ & & $5_13_1$ & $0_11_1$ & & &\
$5_1$ & & $0_13_1$ & & $6_14_1$ & $1_12_1$ & &\
$6_1$ & & & $1_14_1$ & & $0_15_1$ & $2_13_1$ &\
$0_2$ & $2_35_2$ & & & $3_34_2$ & & & $1_36_2$\
$1_2$ & & $4_35_2$ & & $2_30_2$ & & $3_36_2$ &\
$2_2$ & & $3_31_2$ & $5_36_2$ & & & & $4_30_2$\
$3_2$ & & & $4_32_2$ & $5_31_2$ & $6_30_2$& &\
$4_2$ & $0_31_2$ & $6_32_2$ & & & $5_33_2$ & &\
$5_2$ & $6_34_2$ & & $0_33_2$ & & & $1_32_2$ &\
$6_2$ & & & & & $1_34_2$ & $0_35_2$ & $2_33_2$\
$0_3$ & $2_25_3$ & & & $3_24_3$ & & & $1_26_3$\
$1_3$ & & $4_25_3$ & & $2_20_3$ & & $3_26_3$ &\
$2_3$ & & $3_21_3$ & $5_26_3$ & & & & $4_20_3$\
$3_3$ & & & $4_22_3$ & $5_21_3$ & $6_20_3$ & &\
$4_3$ & $0_21_3$ & $6_22_3$ & & & $5_23_3$ & &\
$5_3$ & $6_24_3$ & & $0_23_3$ & & & $1_22_3$ &\
$6_3$ & & & & & $1_24_3$ & $0_25_3$ & $2_23_3$\

**Figure 24**

Which leaves us free to put $\{\infty, x_1\}$ into $(x_1,x_1)$ and
$\{x_2,x_3\}$ into $(x_1,(x\phi _1)_1)$\
e.g. $\{1_2,1_3\}$ can go into $(2_1,(2\phi _1)_1)=(2_1,3_1)$. The
permutation chosen ensures that cell $(2,3)$ of the original square is
empty.\
\
Filling in the rest of block $R11$ gives:

<span>|c|c|c|c|c|c|c|c|</span>

  ------
   Col/
   Row
  ------

& $0_1$ & $1_1$ & $2_1$ & $3_1$ & $4_1$ & $5_1$ & $6_1$\
$0_1$ & $\infty,0_1$ & $0_20_3$ & & $2_15_1$ & & $1_16_1$ & $3_14_1$\
$1_1$ & $4_15_1$ & $\infty, 1_1$ & $1_21_3$ & & $3_16_1$ & & $2_10_1$\
$2_1$ & $3_11_1$ & $5_16_1$ & $\infty,2_1$ & & $2_22_3$ & $4_10_1$ &\
$3_1$ & $3_23_3$ & $4_12_1$ & $6_10_1$ & $\infty,3_1$ & & & $5_11_1$\
$4_1$ & $6_12_1$ & & $5_13_1$ & $0_11_1$ & $\infty,4_1$ & $4_24_3$ &\
$5_1$ & & $0_13_1$ & & $6_14_1$ & $1_12_1$ & $\infty,5_1$ & $5_25_3$\
$6_1$ & & & $1_14_1$ & $6_26_3$ & $0_15_1$ & $2_13_1$ & $\infty,6_1$\

**Figure 25**

Notice that this satisfies the row and column properties of a Room
square for the first seven rows and columns.\
\
Next we move onto the second diagonal block, because missing from row
and column $x_2$ are the elements $\infty, x_1,x_2,x_3$. However this
time we try to find a home for pairs of the form $\{\infty,x_2\}$ and
$\{x_1,x_3\}$.\
\
We can put pairs of the form $\{x_1,x_3\}$ down the diagonal and permute
the columns of block $R_{22}$ with a permutation from Lemma 3.8.1 to
ensure that column $(x\phi _2)_2$ has no $x_2$, allowing us to put
$\{\infty,x_2\}$ in that column.\
\
For instance, using $\phi _2$ we can complete block $R_{13}$, and the
corresponding seven rows and columns, by putting:

$\{x_1,x_3\}$ in $x_2,x_2$\
and $\{\infty,x_2\}$ in $x_2,(x \phi _2)_2$\

Taking the same approach with the third diagonal block we permute
columns in $R_{33}$ using $\phi _3$[^9] and fill-in by putting:

$\{x_1,x_2\}$ in $x_3,x_3$\
and $\{\infty,x_3\}$ in $x_3,(x \phi _3)_3$\

Which results in a Room square of side 21 based on:
$$S = \{\infty,0_1,1_1,...,6_1,0_2,1_2,...,6_2,0_3,1_3,...,6_3\}$$ This
square is straightforwardly transformed to a Room square based on
$\{\infty,0,1,...,20\}$, Figure 26, by using: $$x_i=x+7(i-1)$$ We could
have done this from the beginning, but it is perhaps simpler to keep
track of the missing elements by maintaining the subscript notation.\
\
The preceding triplication was slightly contrived because the
arrangement of frames at the beginning was so chosen because it
satisfied a property as yet unexplained. This property being that the
$R_{ij}$ and $R_{ji}$ occur in the same super-column of the array as
frames. Clearly this must be so in order that permutations, when applied
to both or neither of $R_{ij}$ and $R_{ji}$, preserve the contents of
the columns as far as is required.\
\
That an arrangement of frames with this property can be guaranteed to
exist for any odd integer is fundamental to the generalised theorem.

#### Lemma 3.8.2

\
For all odd $n$ there exists an array with these properties:

1.  the entries of the array consist of all the ordered pairs of the set
    $N=\{1,2,...,n\}$ once each.

2.  the entries of a given row or column contain between them every
    member of $N$ once as a left member and once as a right member.

3.  if $(x,y)$ occurs in a given column of the array $(y,x)$ also occurs
    in that column.

*Proof*\
$A_n$ is an $n \times n$ array whose $(i,j)$ entry is the ordered pair
$(j-i+1,i+j-1)$ with both elements being reduced modulo $n$ to lie on
the interval $[1,n]$.

1.  There are clearly $n^2$ ordered pairs obtainable from $N$. $A_n$ has
    $n^2$ cells, so it is only necessary to show that each cell contains
    a unique pair. For that reason consider any two pairs from different
    cells, $(x_1,y_1)$ and $(x_2,y_2)$, for these to be equal requires
    both,

    $x_1=x_2$ and $y_1=y_2$

    Now, $x_1 = x_2$ $$\Rightarrow j_1-i_1 + 1 = j_2-i_2+1$$ While,
    $y_1=y_2$ $$\Rightarrow i_1+j_1 - 1 = i_2+j_2-1$$ Together these
    imply, $$j_1-i_1=j_2-i_2 \hspace{1cm}(1)$$
    $$i_1+j_1=i_2+j_2 \hspace{1cm}(2)$$ (2) gives, $j_2=i_1+j_1-i_2$,
    which on substitution in (1) gives, $$j_1-i_1=i_1+j_1-2i_2$$
    $$\Rightarrow 2i_1-2i_2=0$$ $$\therefore i_1=i_2$$ Substituting this
    into either expression gives $j_1 = j_2$.\
    Thereby contradicting the assumption that the pairs occurred in
    different cells. Hence every cell contains a unique pair, so all the
    ordered pairs from $N$ occur exactly once in $A_n$.

2.  Consider row $i$ of $A_n$:

         $j=1$        $j=2$      ...     $j=-1$        $j=0$
      ----------- ------------- ----- ------------ -------------
       $(2-i,i)$   $(3-i,i+1)$   ...   $(-i,i-2)$   $(1-i,i-1)$

    Left hand members are $\{2-i,3-i,...,1-i\}$, while the right hand
    members are $\{i,i+1,...,i-1\}$. Both sets contain $n$ unique
    integers on the interval $[1,n]$ and hence both sets must be $N$,
    Similarly, consider column $j$, the left hand positions are occupied
    by $\{j,j-1,...,j+2,j+1\}$, while the right contain
    $\{j,j+1,...,j-2,j-1\}$. For the same reasons both these sets are
    equal to $N$.

3.  Consider a pair $(x,y)$, from the definition of $A_n$,\
    $x=j-i+1$\
    $y=i+j-1$\
    $x+y=j-i+1+i+j-1=2j$\
    $\therefore j= \frac{1}{2} (x+y)$\
    So if $(x,y)$ is in column $j$ of $A_n$ then so is $(y,x)$, since
    $\frac{1}{2}(x+y)=\frac{1}{2}(y+x)$.

We can now present the general result.

#### Theorem 3.8.1 [25]

\
If $r$ and $n$ are odd integers such that $r \geq n$, and if there is a
Room square $R$ of side $r$, then there is a Room square of side $rn$.\
\
*Proof*\
Let $r=2d+1$ and $n=2t+1$.\
For a given $i$ select $n$ permutations as follows:

1.  $\phi _{jk} = \phi _{jl}$ if, and only if, $(k,l)$, and $(l,k)$
    appear in column $j$ of $A_n$.

2.  If cell $(j,j)$ of $A_n$ contains $(x,y)$ then
    $\phi _{jx}=\phi _{jy}=id$ (the identity permutation).

3.  All the $\phi _{jk} (\neq id)$ are selected from the permutations
    associated with $R$, according to Lemma 3.8.1

Now a Room square of side $rn$ is constructed by replacing each entry
$(k,l)$ of $A_n$ by $R_{kl} \phi _{jk}$ (the array $R_{kl}$ under the
column permutation $\phi _{jk}$), where $(k,l)$ is in column $j$ of
$A_n$.\
\
The resulting array has each element of,
$$S = \{0_1,1_1,...,(r-1)_1,0_2,1_2,...,(r-1)_2,0_n,1_n,...,(r-1)_n\}$$
appearing exactly once in each row and column, except that $x_j$ is
missing from row and column $x_j,$
$1 \leq j \leq n \hspace{0.4cm} 0 \leq x \leq (r-1)$, and $x_k$ and
$x_l$ are missing from column $(x \phi _{jk})_j$ for each entry $(k,l)$
in column $j$ of $A_n$.\
\
The array also contains every unordered pair from $S$ exactly once,
except those of the form $\{x_k,x_l\}$.\
Now, for each $k$, if $(k,l)$ is an entry of column $j$ of $A_n$ put
$\{x_k,x_l\}$ in $(x_j,(x \phi _{jk})_j)$, using $\{\infty, x_j\}$
instead of $\{x_j,x_j\}$ in every case.\
\
The completed array contains each of $\{\infty\} \cup S$ exactly once
per row and column and every unordered pair from the same set exactly
once.\
\
Finally, map $\{\infty\} \cup S$ onto $\{\infty \} \cup Z_{rn}$ by
replacing every $x_i$ by $x+r(i-1)$. The finished array is a Room square
of side $rn$.\
\
*Example*\
Looking back at the previous example of triplication.

$A_3 = $

        1     2     3
  --- ----- ----- -----
   1   1,1   2,2   3,3
   2   3,2   1,3   2,1
   3   2,3   3,1   1,2

Now, in column 1 (3,2) and (2,3) both appear, so
$$\phi _{13} = \phi _{12}$$ While in column 2 occur both (1,3) and
(3,1), so $$\phi _{21} = \phi _{23}$$ Furthermore, both (2,1) and (1,2)
appear in the third column, so $$\phi _{32} = \phi _{31}$$ The diagonal
pairs are (1,1),(1,3),(1,2) so
$\phi _{11}=\phi _{21}=\phi _{23}=\phi _{31}=\phi _{32}=id$\
The remaining permutations,
$\phi _{12},\phi _{13},\phi _{22},\phi _{33}$ are chosen according to
the Lemma 3.8.1 and the following array is the Room square in Fig 26
once the missing pairs have been placed and the transformation to
$\{\infty, 0, 1, ..., 20\}$ made.

   $R_{11}\phi _{11}$   $R_{22}\phi _{22}$   $R_{33}\phi _{33}$
  -------------------- -------------------- --------------------
   $R_{32}\phi _{13}$   $R_{13}\phi _{21}$   $R_{21}\phi _{32}$
   $R_{23}\phi _{12}$   $R_{31}\phi _{23}$   $R_{12}\phi _{31}$

$=$

      $R_{11}id$       $R_{22}\phi _{2}$   $R_{33}\phi _{3}$
  ------------------- ------------------- -------------------
   $R_{32}\phi _{1}$      $R_{13}id$          $R_{21}id$
   $R_{23}\phi _{1}$      $R_{31}id$          $R_{12}id$
